version: "3.7"
services:
  jenkins:
    container_name: jenkins
    image: ericnaglertw/cd4ml-build-master:2
    ports:
      - "10000:8080"
    environment:
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
      TENANT: "jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
    secrets:
      - jenkins-admin-password
    networks:
      - jenkins_nw

  mlflow:
    container_name: mlflow
    image: ericnaglertw/cd4ml-mlflow:1
    ports:
      - "12000:5000"
    networks:
      - jenkins_nw

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  jenkins_home:
    driver: local
  data01:
    driver: local

networks:
  jenkins_nw:
    driver: bridge

secrets:
  jenkins-admin-password:
    file: ./jenkins/jenkins-admin-password.txt